<?php require_once './templates2/header.phtml' ?>

<form method='POST' action='add-new-movie'>
    <div class="form-group">
      <label for="nombrePelicula">Titulo</label>
      <input type="text" class="form-control" id="nombreJuego" name='nombreTitulo' placeholder="Titulo de la pelicula">
    </div>
    <div class="form-group">
      <label for="Anio">Anio</label>
      <input type="int" class="form-control" id="Anio" name='Anio' placeholder="Año">
    </div>
    <div class="form-group">
        <label for="Genero">Genero</label>
        <input type="text" min='0' class="form-control" id="Genero" name='Genero' placeholder="Genero">
    </div>
    <div class="form-group">
    <label>Id_Director</label>

                
                <select required name="Id_Director" class="form-control">
                <?php foreach($dirs as $dir) {?>
                    <option value="<?php echo $dir->id ?>"><?php echo $dir->Nombre ?></option>
                <?php }?>
                </select>


    </div>
    
    
    <button type="submit" class="btn btn-primary">Agregar</button>
</form>

<?php require_once './templates2/footer.phtml' ?>