<?php require_once './templates2/header.phtml' ?>

<form method='POST' action='movie-edited/<?= $movie->id ?>'>
    <div class="form-group">
      <label for="nombreJuego">Nombre</label>
      <input type="text" class="form-control" id="nombreJuego" name='nombreJuego' placeholder="Nombre del juego" value='<?= $movie->Titulo ?>'>
    </div>
    <div class="form-group">
      <label for="Anio">Anio</label>
      <input type="number" class="form-control" id="Anio" name='Anio' placeholder="Anio" value='<?= $movie->Anio ?>'>
    </div>
    <div class="form-group">
            <label>Genero</label>
                <select required name="Genero" class="form-control">
                    <option value="Accion">Accion</option>
                    <option value="Aventura">Aventura</option>
                    <option value="Drama">Drama</option>
                    <option value="Ciencia ficcion">Ciencia ficcion</option>
                    <option value="Terror">Terror</option>
                    <option value="Thriller">Thriller</option>

                </select>

    </div>
    <div class="form-group">
    <label>Director</label>
                <select required name="Director" class="form-control">
                  <?php foreach($dirs as $dir) {?>
                    <option value="<?php echo $dir->id ?>"><?php echo $dir->Nombre ?></option>
                  <?php } ?>
                </select>
    </div>
    
    <button type="submit" class="btn btn-primary">Editar</button>
</form>

<?php require_once './templates2/footer.phtml' ?>