<?php require './templates2/header.phtml' ?>

<form method="POST" action="auth">
  <div class="form-group">
    <label for="user">Usuario</label>
    <input type="text" class="form-control" id="user" name="user" placeholder="Usuario">
  </div>
  <div class="form-group">
    <label for="password">Contraseña</label>
    <input type="password" class="form-control" id="password" name="password" placeholder="Contraseña">
  </div>
  <button type="submit" class="btn btn-primary">Ingresar</button>
  <?php if ($message != null): ?>
  <div>
    <p><?= $message ?></p>
  </div>
  <?php endif ?>
</form>

<?php require './templates2/footer.phtml' ?>